 repos:
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]
    - id: pyright
      name: pyright
      language: system
      types: [python]
      entry: pyright
  