 repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]
    - id: pyright
      name: pyright
      language: system
      types: [python]
      entry: pyright
    - id: isort
      name: isort
      language: system
      types: [python]
      entry: isort
    - id: pylint
      name: pylint
      language: system
      types: [python]
      entry: pylint
